# Generated by Django 6.1.1 on 2026-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_details_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
