# Generated by Django 6.1.1 on 2026-09-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producut_name',
            new_name='product_name',
        ),
    ]
